import React from 'react';
import type { Metadata } from 'next';
import './styles/globals.scss';
import { RalewayFont } from './fonts';
import { Header } from './components/generic/Header/Header';
import { clsx } from 'clsx';
import styles from './layout.module.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(RalewayFont.className, styles.layout)}>
        <Header />
        {children}
      </body>
    </html>
  );
}
